### ISSUE TITLE
(Urgent) converting from mirror iso 10303 repo to annotated EXPRESS repo iso-10303 commented out?

### ISSUE THREAD

**Issue by TRThurman** [metanorma/iso-10303-stepmod-annotate#13]
@CAMOBAP 
Do you know why the migration code is commented out in the conversion to annotated express script?
We are trying to do annotation and SUMA builds of the SRL to validate our updates in the ISO Bitbucket repo and Ron is unavailable.
We don't need to use Github for this but need to understand the workflow in order to proceed.
CC: @ronaldtse , @stuartgalt @considiner-boeing

**Comment by ronaldtse** [comment]
@TRThurman as mentioned in today's call, the automated annotation/migration process has been stopped since we incorporated the PDF parts properly, and ensured that the entire repository builds and links properly.

Currently the way to manage the repository is through running the "re-build" process (https://github.com/metanorma/iso-10303#re-building-this-repository) whenever there are changes.

I am running the process as we speak and will now carry a patch (thank you for the suggestion) perhaps that we could use to apply to an automated migration process. We could also take an approach to use a PR instead of direct incorporation to make it clearer on what exactly has changed.

The PR will be made to iso-10303.

**Comment by ronaldtse** [comment]
Closing for now.
